# Valid formatters: <reason>, <time>, <end>
ban-message: "§4BANNED§r: <reason>\n\n§rThis ban will last for: §c<time>§r\n\n§rExpiring at: §c<end>§r"

# Command appearances.
no-undo: "Nothing to do here!"
# Valid formatters: <name>, <punishment>
unpunish-success: "§a<name>§7 successfully un<punishment>!"
# Valid formatters: <name>
invalid-target: "§c<name>§7 is an invalid target!"

# Chat appearance
chat-prefix: "§8§l[§b§lControl§8§l]§r"
chat-header: "§8§l§m------------§8§l[§b§lControl§8§l]§8§l§m------------§r"

# For automatic advertisement punishment
# Valid values: "mute", "ban", "banip"
punishment-type: "mute"
# #<m/h/d/w>
# 10m - 10 minutes
# 1d    - 1 day
# 3h  - 3 hours
# etc.
punishment-length: "5m"
# Part of server's description goes here. Used for not recognizing us as an ad
home: "A Minecraft Server"
adblock-enabled: true
ad-check-message: "§7Are you advertising? Give us a minute to check..."
not-ad-message: "§7You're not advertising. Sorry about that."

# Valid values: "sqlite"
# MySQL will be added soon(TM)
# NEVER CHANGE THIS ONCE IT HAS BEEN SET
sql-mode: "sqlite"

# Commands that cmute will block
# Empty array blocks all commands
cmute-blocked-cmds: []

# Whether or not typing 'welc' in chat sends 'Welcome, <last player to log in>!'
welc-enabled: true

# Whether or not to prevent a player from sending PMs when he or she is muted
block-pms-when-muted: true
