name: SkirtsControl
main: me.curlpipesh.control.Control
version: 0.2.0
description: skirts' plugin for banning and whatnot
authors: [skirts]
website: https://curlpipesh.me/
depend: [Essentials, SkirtsUsers, SkirtsUtil]

permissions:
  control.*:
    description: All control permissions
    children:
      control.channels.adminchat: true
      control.channels.opchat: true
      control.channels.use: true
      control.audit: true
      control.ban: true
      control.banip: true
      control.clearchat: true
      control.cmute: true
      control.history: true
      control.info: true
      control.kick: true
      control.mute: true
      control.online: true
      control.ops: true
      control.plgrep: true
      control.unban: true
      control.unbanip: true
      control.uncmute: true
      control.unmute: true
      control.warn: true
      control.warns: true
    default: op
  control.channels.adminchat:
    description: Allows use of the AdminChat channel
    default: op
  control.channels.opchat:
    description: Allows use of the OpChat channel
    default: op
  control.channels.use:
    description: Allows usage of the various channels
    default: op
  control.audit:
    description: Allows use of the /audit command
    default: op
  control.ban:
    description: Allows use of the /ban command
    default: op
  control.banip:
    description: Allows use of the /banip command
    default: op
  control.clearchat:
    description: Allows use of the /cc command
    default: op
  control.cmute:
    description: Allows use of the /cmute command
    default: op
  control.history:
    description: Allows use of the /history command
    default: op
  control.info:
    description: Allows use of the /info command
    default: op
  control.kick:
    description: Allows use of the /kick command
    default: op
  control.mute:
    description: Allows use of the /mute command
    default: op
  control.online:
    description: Allows use of the /o command
  control.ops:
    description: Allows use of the /ops command
    default: op
  control.plgrep:
    description: Allows use of the /plgrep command
    default: op
  control.unban:
    description: Allows use of the /unban command
    default: op
  control.unbanip:
    description: Allows use of the /unbanip command
    default: op
  control.uncmute:
    description: Allows use of the /uncmute command
    default: op
  control.unmute:
    description: Allows use of the /unmute command
    default: op
  control.warn:
    description: Allows use of the /warn command
    default: op
  control.warns:
    description: Allows use of the /warns command
    default: op