name: Control
main: me.curlpipesh.control.Control
version: 0.1.0
description: skirts' plugin for banning and whatnot
authors: [skirts]
website: http://curlpipesh.me/
depend: [Essentials]

commands:
  a:
    description: Enter admin chat
    usage: /<command>
    permission: control.channels.use
  audit:
    description: Shows all punishments issued by a player
    usage: /<command> <player>
    permission: control.audit
  ban:
    description: Bans a player
    usage: /<command> <player> [length] [reason]
    permission: control.ban
  banip:
    description: Bans an IP
    usage: /<command> <player|IP> [length] [reason]
    permission: control.banip
  cc:
    description: Alias of /clearchat
    usage: /<command>
    permission: control.cc
  channel:
    description: Change admin chat channels, or list available channels
    usage: /<command> [channel]
    permission: control.channels.use
  clearchat:
    description: Clears the chat
    usage: /<command>
    permission: control.clearchat
  cmute:
    description: Prevents a player from using commands
    usage: /<command> <player> [length] [reason]
    permission: control.cmute
  history:
    description: Shows all punishments for a player
    usage: /<command> <player>
    permission: control.history
  kick:
    description: Kicks a player
    usage: /<command> <player>
    permission: control.kick
  mute:
    description: Prevents a player from sending messages
    usage: /<command> <player> [length] [reason]
    permission: control.mute
  o:
    description: Shows the number of players online
    usage: /<command>
    permission: control.online
  ops:
    description: Show all operators
    usage: /<command>
    permission: control.ops
  unban:
    description: Unbans a player
    usage: /<command> <player>
    permission: control.unban
  unbanip:
    description: Unbans an IP
    usage: /<command> <player|IP>
    permission: control.unbanip
  uncmute:
    description: Undoes a command-mute
    usage: /<command> <player>
    permission: control.uncmute
  unmute:
    description: Unmutes a player
    usage: /<command> <player>
    permission: control.unmute
  warn:
    description: Issues a warning to a player
    usage: /<command> <player> [reason]
    permission: control.warn
  warns:
    description: Shows all warnings for a player
    usage: /<command> <player>
    permission: control.warns

permissions:
  control.*:
    description: All control permissions
    children:
      control.channels.adminchat: true
      control.channels.opchat: true
      control.channels.use: true
      control.audit: true
      control.ban: true
      control.banip: true
      control.clearchat: true
      control.cmute: true
      control.history: true
      control.mute: true
      control.online: true
      control.ops: true
      control.unban: true
      control.unbanip: true
      control.uncmute: true
      control.unmute: true
      control.warn: true
      control.warns: true
    default: op
  control.channels.adminchat:
    description: Allows use of the AdminChat channel
    default: op
  control.channels.opchat:
    description: Allows use of the OpChat channel
    default: op
  control.channels.use:
    description: Allows usage of the various channels
    default: op
  control.audit:
    description: Allows use of the /audit command
    default: op
  control.ban:
    description: Allows use of the /ban command
    default: op
  control.banip:
    description: Allows use of the /banip command
    default: op
  control.clearchat:
    description: Allows use of the /cc command
    default: op
  control.cmute:
    description: Allows use of the /cmute command
    default: op
  control.history:
    description: Allows use of the /history command
    default: op
  control.kick:
    description: Allows use of the /kick command
    default: op
  control.mute:
    description: Allows use of the /mute command
    default: op
  control.online:
    description: Allows use of the /o command
  control.ops:
    description: Allows use of the /ops command
    default: op
  control.unban:
    description: Allows use of the /unban command
    default: op
  control.unbanip:
    description: Allows use of the /unbanip command
    default: op
  control.uncmute:
    description: Allows use of the /uncmute command
    default: op
  control.unmute:
    description: Allows use of the /unmute command
    default: op
  control.warn:
    description: Allows use of the /warn command
    default: op
  control.warns:
    description: Allows use of the /warns command
    default: op